Disable notifications in `brew autoupdate`
Our `brew autoupdate` script relied on the program `terminal-notifier`
to display notifications in macOS' Notification Center.

However, `terminal-notifier` has been fatally broken in recent versions,
and just hangs forever when run, never doing anything, never returning.
This caused our script to hang forever, waiting for `terminal-notifier`
to exit.

To temporarily fix this, I've removed the call to the
`terminal-notifier` command. This means the script can no longer show
notifications. This, arguably, makes it useless. But oh well, maybe it
can be fixed in the future...

This commit also adds error handling to the `brew autoupdate uninstall`
subcommand, which checks to make sure the agent is actually installed
before trying to uninstall it. If it isn't, it just shows an error
message and exits.

diff --git a/home/bin/mac/brew-autoupdate b/home/bin/mac/brew-autoupdate
--- a/home/bin/mac/brew-autoupdate
+++ b/home/bin/mac/brew-autoupdate
@@ -68,10 +68,15 @@ agent_install() {
 
 # Uninstall launch agent
 agent_uninstall() {
-    echo "Uninstalling agent at $AGENT_PATH"
+    if ! [[ -e "$AGENT_PATH" ]]; then
+        echo "Error: agent not currently installed" >&2
+        exit 50
+    fi
+
+    echo "Uninstalling agent \"${AGENT_PATH/#$HOME/'~'}\"..."
 
     launchctl unload "$AGENT_PATH"
-    rm "$AGENT_PATH"
+    command rm "$AGENT_PATH"
 }
 
 
@@ -153,24 +158,33 @@ get_outdated() {
 
 
 show_notification() {
-    local outdated_packages="$1"
-    [[ -x /usr/local/bin/terminal-notifier ]] || return 1
+    #######
+    # Recent versions of `terminal-notifier` are completely broken. Running it seems to cause it to
+    # just hang indefinitely, and never exit. That causes this script to hang and never exit.
+    # Just to allow this script to run without hanging, the function is now a noop. This makes this
+    # entire script arguably pointless, but at least it will no longer be hazardous.
+    #######
+    return 0
 
-    if [[ -z "$outdated_packages" ]]; then
-        /usr/local/bin/terminal-notifier -remove "$NOTIFICATION_GROUP_ID"
-        return 0
-    fi
 
-    # Format the outdated package name from 'package (old < new)' to 'package vnew'
-    local outdated_formatted="$(printf '%s' "$outdated_packages" | sed -E -e 's/^(.+) \(([^<)]+) < ([^ )]+)\)$/\1 (\3)/g')"
-    # Replace newlines with ', '
-    local outdated_text="$(printf '%s %s, ' $outdated_formatted)"
-    # Cut off the last ", "
-    local outdated_merged="${outdated_text:0:-2}"
+    #local outdated_packages="$1"
+    #[[ -x /usr/local/bin/terminal-notifier ]] || return 1
 
-    local beer_emoji='🍺'
+    #if [[ -z "$outdated_packages" ]]; then
+        #/usr/local/bin/terminal-notifier -remove "$NOTIFICATION_GROUP_ID"
+        #return 0
+    #fi
 
-    /usr/local/bin/terminal-notifier -title "${beer_emoji} Updates Available" -message "$outdated_merged" -group "$NOTIFICATION_GROUP_ID" -activate com.apple.Terminal
+    ## Format the outdated package name from 'package (old < new)' to 'package vnew'
+    #local outdated_formatted="$(printf '%s' "$outdated_packages" | sed -E -e 's/^(.+) \(([^<)]+) < ([^ )]+)\)$/\1 (\3)/g')"
+    ## Replace newlines with ', '
+    #local outdated_text="$(printf '%s %s, ' $outdated_formatted)"
+    ## Cut off the last ", "
+    #local outdated_merged="${outdated_text:0:-2}"
+
+    #local beer_emoji='🍺'
+
+    #/usr/local/bin/terminal-notifier -title "${beer_emoji} Updates Available" -message "$outdated_merged" -group "$NOTIFICATION_GROUP_ID" -activate com.apple.Terminal
 }
 
 
