Git: update template to allow commit msg headers up to 72 chars
This is an increase from the previous 50 char limit, and reflects the
latest Linux kernel git repo patch guidelines (which give a hard limit
of 70-75 characters, and a suggested limit of 50 chars.)

diff --git a/home/.gitsupport/template/hooks/commit-msg b/home/.gitsupport/template/hooks/commit-msg
--- a/home/.gitsupport/template/hooks/commit-msg
+++ b/home/.gitsupport/template/hooks/commit-msg
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-if head -n 1 "$1" | grep -E '^.{51,}'; then
-	echo "Error: Summary too long (must be <= 50 characters)" >&2
+if head -n 1 "$1" | grep -E '^.{72,}'; then
+	echo "Error: Summary too long (must be <= 72 characters)" >&2
 	exit 1
 fi
 
